version: '3.10.18'

services:
  telegram-bot:
    build: .
    container_name: rag-bot
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_DB: rag_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: